"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"preserve_hierarchy": true

files:
  - source: /frontend/src/locales/en/*.json
    translation: /frontend/src/locales/%two_letters_code%/%original_file_name%
